title: Hello, world! I'm Rishab Mudliar
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "lazycodes7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rishab Mudliar # add your name
author-img: rishabmudliar.jpeg # add your photo
about-author: I am a student currently exploring the field of IoT and Android. # add description
social-twitter: HSrishab
social-facebook: rishab.mudliar.1
social-github: lazyCodes7 # add your Github handle
social-linkedin: /rishab-mudliar-8022171b1
social-email: rishabmudliar@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
